"""Trainer module - Unsloth notebook template generation, Colab-ready output."""

import json
from pathlib import Path
from typing import Any, Dict, List, Optional
from uuid import UUID

import structlog
from jinja2 import Template

from synthetic_data_flywheel.config import get_settings
from synthetic_data_flywheel.models import SyntheticPair

logger = structlog.get_logger()


# Unsloth Training Notebook Template
UNSLOTH_NOTEBOOK_TEMPLATE = '''{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 🦥 Unsloth Fine-tuning Notebook\\n",
    "\\n",
    "Generated by Synthetic Data Flywheel - Cycle {{ cycle_id }}\\n",
    "\\n",
    "This notebook fine-tunes a model using the synthetic dataset generated by the flywheel."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Install dependencies\\n",
    "!pip install unsloth torch transformers datasets trl\\n",
    "!pip install bitsandbytes accelerate"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from unsloth import FastLanguageModel\\n",
    "import torch\\n",
    "\\n",
    "# Configuration\\n",
    "max_seq_length = {{ max_seq_length }}\\n",
    "dtype = {{ dtype }}\\n",
    "load_in_4bit = {{ load_in_4bit }}\\n",
    "\\n",
    "model_name = \\"{{ base_model }}\\"\\n",
    "\\n",
    "model, tokenizer = FastLanguageModel.from_pretrained(\\n",
    "    model_name=model_name,\\n",
    "    max_seq_length=max_seq_length,\\n",
    "    dtype=dtype,\\n",
    "    load_in_4bit=load_in_4bit,\\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Setup LoRA\\n",
    "model = FastLanguageModel.get_peft_model(\\n",
    "    model,\\n",
    "    r={{ lora_r }},\\n",
    "    target_modules=[\\n",
    "        \\"q_proj\\", \\"k_proj\\", \\"v_proj\\", \\"o_proj\\",\\n",
    "        \\"gate_proj\\", \\"up_proj\\", \\"down_proj\\",\\n",
    "    ],\\n",
    "    lora_alpha={{ lora_alpha }},\\n",
    "    lora_dropout={{ lora_dropout }},\\n",
    "    bias=\\"none\\",\\n",
    "    use_gradient_checkpointing=\\"unsloth\\",\\n",
    "    random_state=3407,\\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load dataset\\n",
    "from datasets import load_dataset\\n",
    "\\n",
    "# Load the synthetic dataset\\n",
    "dataset = load_dataset(\\"json\\", data_files=\\"{{ dataset_path }}\\")\\n",
    "train_dataset = dataset[\\"train\\"]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Format dataset for training\\n",
    "alpaca_prompt = \\"\\"\\"Below is an instruction that describes a task. Write a response that appropriately completes the request.\\n",
    "\\n",
    "### Instruction:\\n",
    "{}\\n",
    "\\n",
    "### Response:\\n",
    "{}\\"\\"\\"\\n",
    "\\n",
    "EOS_TOKEN = tokenizer.eos_token\\n",
    "\\n",
    "def formatting_prompts_func(examples):\\n",
    "    instructions = examples[\\"instruction\\"]\\n",
    "    outputs = examples[\\"output\\"]\\n",
    "    texts = []\\n",
    "    for instruction, output in zip(instructions, outputs):\\n",
    "        text = alpaca_prompt.format(instruction, output) + EOS_TOKEN\\n",
    "        texts.append(text)\\n",
    "    return {\\"text\\": texts}\\n",
    "\\n",
    "train_dataset = train_dataset.map(formatting_prompts_func, batched=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Setup trainer\\n",
    "from trl import SFTTrainer\\n",
    "from transformers import TrainingArguments\\n",
    "\\n",
    "trainer = SFTTrainer(\\n",
    "    model=model,\\n",
    "    tokenizer=tokenizer,\\n",
    "    train_dataset=train_dataset,\\n",
    "    dataset_text_field=\\"text\\",\\n",
    "    max_seq_length=max_seq_length,\\n",
    "    dataset_num_proc=2,\\n",
    "    packing=False,\\n",
    "    args=TrainingArguments(\\n",
    "        per_device_train_batch_size={{ batch_size }},\\n",
    "        gradient_accumulation_steps={{ gradient_accumulation_steps }},\\n",
    "        warmup_steps={{ warmup_steps }},\\n",
    "        max_steps={{ max_steps }},\\n",
    "        learning_rate={{ learning_rate }},\\n",
    "        fp16=not torch.cuda.is_bf16_supported(),\\n",
    "        bf16=torch.cuda.is_bf16_supported(),\\n",
    "        logging_steps=10,\\n",
    "        optim=\\"adamw_8bit\\",\\n",
    "        weight_decay=0.01,\\n",
    "        lr_scheduler_type=\\"linear\\",\\n",
    "        seed=3407,\\n",
    "        output_dir=\\"{{ output_dir }}\\",\\n",
    "    ),\\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Train\\n",
    "trainer_stats = trainer.train()\\n",
    "print(f\\"Training complete! Final loss: {trainer_stats.training_loss:.4f}\\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Save model\\n",
    "model.save_pretrained(\\"{{ output_dir }}/lora_model\\")\\n",
    "tokenizer.save_pretrained(\\"{{ output_dir }}/lora_model\\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Test inference\\n",
    "FastLanguageModel.for_inference(model)\\n",
    "\\n",
    "inputs = tokenizer(\\n",
    "    [\\n",
    "        alpaca_prompt.format(\\n",
    "            \\"What is the capital of France?\\",\\n",
    "            \\"\\",\\n",
    "        )\\n",
    "    ], return_tensors=\\"pt\\").to(\\"cuda\\")\\n",
    "\\n",
    "outputs = model.generate(\\n",
    "    **inputs,\\n",
    "    max_new_tokens=128,\\n",
    "    use_cache=True,\\n",
    ")\\n",
    "\\n",
    "print(tokenizer.batch_decode(outputs)[0])"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.10.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}'''


class Trainer:
    """Trainer for generating Unsloth fine-tuning notebooks."""
    
    def __init__(
        self,
        output_dir: Optional[str] = None,
        base_model: Optional[str] = None,
    ):
        """Initialize trainer.
        
        Args:
            output_dir: Directory for output notebooks
            base_model: Base model to fine-tune
        """
        settings = get_settings()
        self.output_dir = Path(output_dir or settings.notebook_output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.base_model = base_model or settings.trainer_base_model
        
        self.template = Template(UNSLOTH_NOTEBOOK_TEMPLATE)
        
        logger.info(
            "trainer_initialized",
            output_dir=str(self.output_dir),
            base_model=self.base_model,
        )
    
    def generate_training_notebook(
        self,
        dataset_path: str,
        cycle_id: int,
        config: Optional[Dict[str, Any]] = None,
    ) -> Path:
        """Generate Unsloth training notebook.
        
        Args:
            dataset_path: Path to training dataset
            cycle_id: Current cycle ID
            config: Optional training configuration overrides
            
        Returns:
            Path to generated notebook
        """
        settings = get_settings()
        
        # Default training config
        default_config = {
            "cycle_id": cycle_id,
            "max_seq_length": 2048,
            "dtype": "None",  # Auto-detect
            "load_in_4bit": "True",
            "base_model": self.base_model,
            "lora_r": 16,
            "lora_alpha": 16,
            "lora_dropout": 0,
            "batch_size": 2,
            "gradient_accumulation_steps": 4,
            "warmup_steps": 10,
            "max_steps": 100,
            "learning_rate": 2e-4,
            "dataset_path": dataset_path,
            "output_dir": f"./outputs/cycle_{cycle_id:03d}",
        }
        
        # Merge with provided config
        if config:
            default_config.update(config)
        
        # Render template
        notebook_json = self.template.render(**default_config)
        
        # Parse and save
        notebook_data = json.loads(notebook_json)
        
        output_path = self.output_dir / f"training_cycle_{cycle_id:03d}.ipynb"
        with open(output_path, "w") as f:
            json.dump(notebook_data, f, indent=2)
        
        logger.info(
            "training_notebook_generated",
            path=str(output_path),
            cycle_id=cycle_id,
            base_model=self.base_model,
        )
        
        return output_path
    
    def create_colab_url(self, notebook_path: Path) -> str:
        """Create Google Colab URL for notebook.
        
        Args:
            notebook_path: Path to notebook file
            
        Returns:
            Colab URL
        """
        # For local files, we need to upload to GitHub or use Colab's file upload
        # This creates a URL that opens Colab with instructions
        return f"https://colab.research.google.com/github/placeholder/repo/blob/main/{notebook_path.name}"
    
    def generate_training_config(
        self,
        cycle_id: int,
        config: Optional[Dict[str, Any]] = None,
    ) -> Path:
        """Generate training configuration JSON.
        
        Args:
            cycle_id: Current cycle ID
            config: Optional configuration overrides
            
        Returns:
            Path to generated config
        """
        settings = get_settings()
        
        default_config = {
            "model_name_or_path": self.base_model,
            "output_dir": f"./outputs/cycle_{cycle_id:03d}",
            "num_train_epochs": 3,
            "per_device_train_batch_size": 2,
            "gradient_accumulation_steps": 4,
            "learning_rate": 2e-4,
            "warmup_steps": 10,
            "logging_steps": 10,
            "save_steps": 100,
            "eval_steps": 100,
            "max_seq_length": 2048,
            "lora_r": 16,
            "lora_alpha": 16,
            "lora_dropout": 0.0,
            "use_4bit": True,
            "use_nested_quant": False,
            "bnb_4bit_compute_dtype": "float16",
            "cycle_id": cycle_id,
            "flywheel_version": "0.1.0",
        }
        
        if config:
            default_config.update(config)
        
        output_path = self.output_dir / f"config_cycle_{cycle_id:03d}.json"
        with open(output_path, "w") as f:
            json.dump(default_config, f, indent=2)
        
        logger.info(
            "training_config_generated",
            path=str(output_path),
            cycle_id=cycle_id,
        )
        
        return output_path
    
    def prepare_training_artifacts(
        self,
        pairs: List[SyntheticPair],
        cycle_id: int,
        dataset_manager: Any,  # DatasetManager type
    ) -> Dict[str, Path]:
        """Prepare all training artifacts for a cycle.
        
        Args:
            pairs: Training pairs
            cycle_id: Current cycle ID
            dataset_manager: Dataset manager instance
            
        Returns:
            Dictionary of artifact paths
        """
        # Save dataset
        dataset_path = dataset_manager.save_local(
            pairs,
            filename=f"train_cycle_{cycle_id:03d}.json",
            split="train",
        )
        
        # Generate notebook
        notebook_path = self.generate_training_notebook(
            dataset_path=str(dataset_path),
            cycle_id=cycle_id,
        )
        
        # Generate config
        config_path = self.generate_training_config(cycle_id=cycle_id)
        
        artifacts = {
            "dataset": dataset_path,
            "notebook": notebook_path,
            "config": config_path,
        }
        
        logger.info(
            "training_artifacts_prepared",
            cycle_id=cycle_id,
            artifacts={k: str(v) for k, v in artifacts.items()},
        )
        
        return artifacts


def create_trainer(
    output_dir: Optional[str] = None,
    base_model: Optional[str] = None,
) -> Trainer:
    """Factory function to create a trainer.
    
    Args:
        output_dir: Output directory for notebooks
        base_model: Base model to fine-tune
        
    Returns:
        Configured Trainer
    """
    return Trainer(output_dir=output_dir, base_model=base_model)
