"""Trainer module - Unsloth notebook template generation, Colab-ready output."""

import json
from pathlib import Path
from typing import Any, Dict, List, Optional

from synthetic_data_flywheel.config import get_settings
from synthetic_data_flywheel.models import SyntheticPair


UNSLOTH_NOTEBOOK_TEMPLATE = '''{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 🦥 Unsloth Fine-tuning - Cycle {{ cycle_id }}\\n",
    "Generated by Synthetic Data Flywheel"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "!pip install unsloth torch transformers datasets trl"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from unsloth import FastLanguageModel\\n",
    "import torch\\n",
    "\\n",
    "model, tokenizer = FastLanguageModel.from_pretrained(\\n",
    "    model_name=\\"{{ base_model }}\\",\\n",
    "    max_seq_length={{ max_seq_length }},\\n",
    "    dtype=None,\\n",
    "    load_in_4bit=True,\\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "model = FastLanguageModel.get_peft_model(\\n",
    "    model,\\n",
    "    r={{ lora_r }},\\n",
    "    target_modules=[\\"q_proj\\", \\"k_proj\\", \\"v_proj\\", \\"o_proj\\"],\\n",
    "    lora_alpha={{ lora_alpha }},\\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from datasets import load_dataset\\n",
    "dataset = load_dataset(\\"json\\", data_files=\\"{{ dataset_path }}\\")[\\"train\\"]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from trl import SFTTrainer\\n",
    "from transformers import TrainingArguments\\n",
    "\\n",
    "trainer = SFTTrainer(\\n",
    "    model=model,\\n",
    "    tokenizer=tokenizer,\\n",
    "    train_dataset=dataset,\\n",
    "    dataset_text_field=\\"text\\",\\n",
    "    args=TrainingArguments(\\n",
    "        per_device_train_batch_size={{ batch_size }},\\n",
    "        gradient_accumulation_steps={{ gradient_accumulation_steps }},\\n",
    "        max_steps={{ max_steps }},\\n",
    "        learning_rate={{ learning_rate }},\\n",
    "        output_dir=\\"{{ output_dir }}\\",\\n",
    "    ),\\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "trainer.train()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}'''


class Trainer:
    """Trainer for generating Unsloth fine-tuning notebooks."""
    
    def __init__(
        self,
        output_dir: Optional[str] = None,
        base_model: Optional[str] = None,
    ):
        """Initialize trainer."""
        settings = get_settings()
        self.output_dir = Path(output_dir or settings.notebook_output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.base_model = base_model or settings.trainer_base_model
    
    def generate_training_notebook(
        self,
        dataset_path: str,
        cycle_id: int,
        config: Optional[Dict[str, Any]] = None,
    ) -> Path:
        """Generate Unsloth training notebook."""
        settings = get_settings()
        
        default_config = {
            "cycle_id": cycle_id,
            "max_seq_length": 2048,
            "base_model": self.base_model,
            "lora_r": 16,
            "lora_alpha": 16,
            "batch_size": 2,
            "gradient_accumulation_steps": 4,
            "max_steps": 100,
            "learning_rate": 2e-4,
            "dataset_path": dataset_path,
            "output_dir": f"./outputs/cycle_{cycle_id:03d}",
        }
        
        if config:
            default_config.update(config)
        
        # Simple template rendering
        template = UNSLOTH_NOTEBOOK_TEMPLATE
        for key, value in default_config.items():
            placeholder = "{{ " + key + " }}"
            template = template.replace(placeholder, str(value))
        
        notebook_data = json.loads(template)
        
        output_path = self.output_dir / f"training_cycle_{cycle_id:03d}.ipynb"
        with open(output_path, "w") as f:
            json.dump(notebook_data, f, indent=2)
        
        return output_path
    
    def prepare_training_artifacts(
        self,
        pairs: List[SyntheticPair],
        cycle_id: int,
        dataset_manager: Any,
    ) -> Dict[str, Path]:
        """Prepare all training artifacts for a cycle."""
        # Save dataset
        dataset_path = dataset_manager.save_local(
            pairs,
            filename=f"train_cycle_{cycle_id:03d}.json",
            split="train",
        )
        
        # Generate notebook
        notebook_path = self.generate_training_notebook(
            dataset_path=str(dataset_path),
            cycle_id=cycle_id,
        )
        
        return {
            "dataset": dataset_path,
            "notebook": notebook_path,
        }


def create_trainer(
    output_dir: Optional[str] = None,
    base_model: Optional[str] = None,
) -> Trainer:
    """Factory function to create a trainer."""
    return Trainer(output_dir=output_dir, base_model=base_model)
